upload_form:
    path: /uploadform
    controller: App\Controller\UploadController::form
    methods:  [GET]

process_form:
    path: /uploadform
    controller: App\Controller\UploadController::process
    methods:  [POST]

app_logout:
    path: /logout
